version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  react: # name of the first service
    build: react-client # specify the directory of the Dockerfile
    ports:
      - "3000:3000" # specify port forewarding

  express: #name of the second service
    build: express-api # specify the directory of the Dockerfile
    ports:
      - "9000:9000" #specify ports forewarding
